### ISSUE TITLE
Character encoding issues in manual

### ISSUE THREAD

**Issue by pviotti** [EduMIPS64/edumips64#489]
Some characters in the manual are badly rendered. 

![image](https://user-images.githubusercontent.com/1350095/97033379-2ad8f180-155b-11eb-9738-214fbe81da2b.png)
![image](https://user-images.githubusercontent.com/1350095/97033419-3a583a80-155b-11eb-9bba-3c9ecd2e6a5d.png)
etc.

v1.2.8 on Windows and Linux.

**Comment by lupino3** [comment]
Thanks @pviotti! Curiously enough, it all seems ok on readthedocs: https://edumips64.readthedocs.io/en/latest/

**Comment by lupino3** [comment]
![Screenshot 2020-10-24 at 19 00 41](https://user-images.githubusercontent.com/200139/97088800-44e20500-162b-11eb-9269-7898f293704a.png)
![Screenshot 2020-10-24 at 19 00 26](https://user-images.githubusercontent.com/200139/97088802-4ad7e600-162b-11eb-8881-c8996f7b8dce.png)

Also works on Mac OS X

**Comment by lupino3** [comment]
![image](https://user-images.githubusercontent.com/200139/97088864-b621b800-162b-11eb-9ca5-3ad0b47395b5.png)
The issue is visible even for the JAR built by CI (just excluding a possible misconfiguration of my local desktop where I built the JAR)

**Comment by lupino3** [comment]
Broken even in 1.2.7:
![image](https://user-images.githubusercontent.com/200139/97088985-7d361300-162c-11eb-81c6-96613da117ff.png)

**Comment by lupino3** [comment]
1.2.6 looks better, so the breakage is likely to have happened between 1.2.6 and 1.2.7:
![image](https://user-images.githubusercontent.com/200139/97089001-a6ef3a00-162c-11eb-8b88-4371fcff6cb8.png)

**Comment by lupino3** [comment]
BTW 1.2.8 does not look broken to me on Ubuntu 20.04
![Screenshot from 2020-10-24 21-24-40](https://user-images.githubusercontent.com/200139/97092879-6a790980-163f-11eb-8ae9-059056fea32d.png)
@pviotti what version of Linux are you using?

**Comment by pviotti** [comment]
Arch :) but there's nothing special about [its package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=edumips64), AFAIK. I tried to reinstall previous versions and, as you wrote, 1.2.7 has the same issue, 1.2.6 doesn't. From a quick look at the history the issue might have been introduced by one of these commits:
65424f44131b5766722debab4d094bcdabe8d763
e343883e8349a5f044b82d7236cde44edb474962
0f246d1e758c5a191a9b85c83bd75ed3960eca2b
4d404c7e12dc08be73771fd52ce0d021745fd4e5
e1c678f7c50005d5f5796a26b050a5cc026c664b

Javahelp is [not maintained](https://github.com/javaee/javahelp) anymore, so if this proves difficult to fix it'd be an opportunity to get rid of it (maybe just embedding HTML into the jar and launching a browser would do - though I'm not sure how exactly..).

**Comment by lupino3** [comment]
That's a good point, we aren't really using many JavaHelp features. Maybe we could try a JavaFX WebView: https://stackoverflow.com/questions/13487786/add-webview-control-on-swing-jframe

**Comment by lupino3** [comment]
Just for the record, I tried an old version of Sphinx (2.3.1) but that was not the issue.

I thought a bit about it, and the alternatives to JavaHelp are not great:

1) JavaFX has good rendering but has hundreds of MBs of dependencies and, more importantly, makes it much harder to create a cross-platform JAR;
2) JEditorPane is very primitive and has the same rendering issues that JavaHelp has
3) FlyingSaucer renders as an image, which is not selectable and not searchable.

I currently lean towards
1) trying to fix JavaHelp 
1a) possibly see if it would be possible to use JEditorPane instead of JavaHelp, which would get rid of the JavaHelp dependency while providing similar features.
2) *in parallel* also providing the new feature of opening the manual in an external browser as a fallback, via a separate menu option.

@pviotti what do you think?:

**Comment by pviotti** [comment]
> trying to fix JavaHelp

you mean poking around JavaHelp code and try to see if there's an easy way to fix encoding issues? That can be done, and maybe it would be useful to other projects too, though it can take a long time (if it's possible at all).  
The alternative are not great, indeed (I'm particularly surprised that JEditorPane has encoding and graphics glitches even in the latest JRE versions :confused:)

If you really want to avoid depending on browsers, I suspect it would be easier to embed the documentation in some other format, like PDF.

**Comment by lupino3** [comment]
I meant try to understand where we introduced the regression: 1.2.6 works well and 1.2.7 doesn't -- I'd like to pinpoint what commit introduced the encoding issues and see if that's fixable.

But the PDF idea is also very good, I'll have a look around to see if there are any Swing PDF viewers. A very quick search yielded this library, which I'll now try out: https://mvnrepository.com/artifact/org.icepdf.os/icepdf-core/6.1.2

**Comment by lupino3** [comment]
I tried to use `icepdf` but the artifacts on the Maven repos do not work due to broken dependencies.

The website doesn't mention Maven and the download of the open source JAR is behind a login form: http://www.icesoft.org/java/home.jsf

I found a fork which seems maintained but it's not yet published to a Maven repo. I asked them if they will publish it here: https://github.com/pdf4j/icepdf/issues/7

**Comment by lupino3** [comment]
Well the fork is not really maintained, I got confused with another repo I was looking at.
